name: Update ERC20 data

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - tokens.json

jobs:
  publish:
    environment:
      name: production
      url: "https://www.npmjs.com/package/@celo/ledger-token-signer"
    runs-on: ["self-hosted", "org", "npm-publish"]
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: write

    steps:
      - uses: actions/checkout@v4

      - name: Get NPM Token from Akeyless
        id: get_npmjs_token
        uses: docker://us-west1-docker.pkg.dev/devopsre/akeyless-public/akeyless-action:latest
        with:
          api-url: https://api.gateway.akeyless.celo-networks-dev.org
          access-id: p-kf9vjzruht6l
          static-secrets: |
            {
                "/static-secrets/NPM/npm-publish-token": "NPM_TOKEN"
            }

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org"
          scope: "@celo"

      - run: bun install

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "gh-celo-ledger-token-signer@clabs-secrets-and-permissions.iam.gserviceaccount.com"
          workload_identity_provider: "projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-ledger-token-signer/providers/github-by-repos"

      - name: Export data
        id: export_Data
        run: |
          bun run sign-hsm
          bun run build
        env:
          GCLOUD_PROJECT_ID: "clabs-secrets-and-permissions"
          GCLOUD_LOCATION_ID: "us-west1"
          GCLOUD_KEY_RING_ID: "clabs-ledger-app-tokens-signing-keyring"
          GCLOUD_KEY_ID: "clabs-ledger-app-tokens-signing-key"
          GCLOUD_VERSION_ID: "1"

      - name: Bump version
        id: bump_version
        run: echo "NPM_VERSION=$(npm version minor --no-git-tag-version)" >> $GITHUB_OUTPUT

      - name: Publish
        run: bun publish --access public
#       env:
#          NPM_CONFIG_TOKEN: ${{ env.NPM_TOKEN }}
#          BUN_AUTH_TOKEN: ${{ env.NPM_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: publish ${{ steps.bump_version.outputs.NPM_VERSION }}"
          tagging_message: ${{ steps.bump_version.outputs.NPM_VERSION }}
